# Generated by Django 3.2 on 2022-01-26 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='brettdavidbowles', max_length=200),
            preserve_default=False,
        ),
    ]
