# Generated by Django 3.2 on 2022-04-07 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_transaction_is_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=16),
            preserve_default=False,
        ),
    ]
