# Generated by Django 3.2 on 2022-04-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_profitperday_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='title',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bot',
            name='url',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
    ]
