# Generated by Django 3.2 on 2022-04-19 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20220409_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeprecatedTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sale', models.BooleanField(default=False)),
                ('coin_quantity', models.DecimalField(decimal_places=5, max_digits=16)),
                ('quantity', models.DecimalField(decimal_places=5, max_digits=16)),
                ('bought_price', models.DecimalField(decimal_places=5, max_digits=16)),
                ('sell_price', models.DecimalField(decimal_places=5, max_digits=16)),
                ('transaction_price', models.DecimalField(decimal_places=2, max_digits=16)),
                ('contemporary_coin_price', models.DecimalField(decimal_places=2, max_digits=16)),
                ('transaction_date_time', models.DateTimeField(auto_now_add=True)),
                ('profit', models.DecimalField(decimal_places=5, max_digits=16)),
                ('name', models.CharField(default='default', max_length=200)),
                ('bot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.bot')),
                ('coin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.coin')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
