# Generated by Django 3.2 on 2022-04-20 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20220419_2107'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeprecatedTransaction',
            new_name='DeprecatedTransaction2',
        ),
    ]
