# Generated by Django 3.2 on 2022-04-20 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_deprecatedtransaction_deprecatedtransaction2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeprecatedTransaction2',
            new_name='DeprecatedTransaction',
        ),
    ]
