# Generated by Django 3.2 on 2022-04-20 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='bought_price',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sell_price',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=16),
        ),
    ]
