# Generated by Django 3.2 on 2022-04-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20220420_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='current_price',
            field=models.DecimalField(decimal_places=5, default=4.0, max_digits=16),
            preserve_default=False,
        ),
    ]
