# Generated by Django 3.2 on 2022-05-28 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_transactioncalculations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactioncalculations',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, primary_key=True, serialize=False, to='api.transaction'),
        ),
    ]
