# Generated by Django 3.2 on 2022-05-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_transactioncalculations_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactioncalculations',
            name='cumulative_profit',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactioncalculations',
            name='cumulative_profit_margin',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactioncalculations',
            name='transaction_profit_margin',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
