# Generated by Django 3.2 on 2022-06-03 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20220601_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactioncalculations',
            name='cumulative_revenue',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='transactioncalculations',
            name='transaction_revenue',
            field=models.FloatField(null=True),
        ),
    ]
