# Generated by Django 3.2 on 2022-08-07 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_coin_bot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profitperday',
            name='bot',
        ),
        migrations.RemoveField(
            model_name='profitperday',
            name='coin',
        ),
        migrations.RemoveField(
            model_name='profitperday',
            name='user',
        ),
        migrations.DeleteModel(
            name='DeprecatedTransaction2',
        ),
        migrations.DeleteModel(
            name='ProfitPerDay',
        ),
    ]
